### ISSUE TITLE
Building on ARM arch

### ISSUE THREAD

**Issue by reijosirila** [bengfarrell/node-sweatintotheweb#1]
root@smart-switch:/home/pi/node-sweatintotheweb/src# node-gyp --arch arm build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.11.0
gyp info using node@0.10.21 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/pi/node-sweatintotheweb/src/build'
  CXX(target) Release/obj.target/followthehand/followthehand.o
../followthehand.cpp: In function 'v8::Handle<v8::Value> initialize(const v8::Arguments&)':
../followthehand.cpp:108:71: error: invalid conversion from 'void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}' to 'uv_after_work_cb {aka void (*)(uv_work_s*, int)}' [-fpermissive]
/root/.node-gyp/0.10.21/deps/uv/include/uv.h:1432:15: error:   initializing argument 4 of 'int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)' [-fpermissive]
../followthehand.cpp:109:16: error: too few arguments to function 'int uv_run(uv_loop_t*, uv_run_mode)'
/root/.node-gyp/0.10.21/deps/uv/include/uv.h:273:15: note: declared here
make: *** [Release/obj.target/followthehand/followthehand.o] Error 1
make: Leaving directory`/home/pi/node-sweatintotheweb/src/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.6.11+
gyp ERR! command "node" "/opt/node/bin/node-gyp" "--arch" "arm" "build"
gyp ERR! cwd /home/pi/node-sweatintotheweb/src
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok 
root@smart-switch:/home/pi/node-sweatintotheweb/src#

**Comment by bengfarrell** [comment]
Hey switch on over to https://github.com/bengfarrell/nuimotion. This repo was more of a demo/test thing while I learned how to do motion sensing in Node.js. NuiMotion is the project that came out of the playing.

While I definitely never tried to compile on ARM or a Rasberry Pi, the issue looks like a Node v0.10 issue that I addressed in NuiMotion.

**Comment by reijosirila** [comment]
Hi!

I was able to compile your software (with some modifications), but
unluckily NITE does not support ARM and there is no use to use this on
Raspberry PI. But NITE roadmap shows that it's planned so we might need it
near future still.

But thank you for the information and i'll have look to nuimotion!

Reijo

On Wed, Nov 6, 2013 at 4:34 AM, bengfarrell notifications@github.comwrote:

> Hey switch on over to https://github.com/bengfarrell/nuimotion. This repo
> was more of a demo/test thing while I learned how to do motion sensing in
> Node.js. NuiMotion is the project that came out of the playing.
> 
> While I definitely never tried to compile on ARM or a Rasberry Pi, the
> issue looks like a Node v0.10 issue that I addressed in NuiMotion.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bengfarrell/node-sweatintotheweb/issues/1#issuecomment-27836329
> .[image: Web Bug from
> https://github.com/notifications/beacon/gZT3TRdqeruKJsm8cpuS8_aHw5K1wKJzfAOWkedy-dpQxRIZwpVdSIavoaLYLqlm.gif]

##
